<a href="https://colab.research.google.com/github/user1inna/data-and-python/blob/main/Worksheets/11_Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Cleaning data

Wherever data comes from (a data file, an online source, scraped from a web page, a collection device such as a sensor, or user input as in a survey) there is the potential for it to be inaccurate or invalid.

It could be, for example:
*  the wrong data type
*  in the wrong format
*  missing
*  out of the expected range

When data is read in, it should always be validated.  Inaccurate data can cause inaccurate results.

---
### Get some data to work with

Run the code below to get weather data for Paisley from January 1959 to February 2021.  The code will allow you to take a look at the table, and will show the first 5 rows and the last 5 rows.

In [2]:
import pandas as pd

def get_data():
  url = "https://raw.githubusercontent.com/futureCodersSE/working-with-data/main/Data%20sets/Paisley-Weather-Data.csv"
  df = pd.read_csv(url)
  return df

weather_data = get_data()
display(weather_data)

,yyyy,mm,tmax (degC),tmin (degC),af (days),rain (mm),sun (hours),status
0,1959,1,4,-2,25,40.9,54.1,NaN
1,1959,2,6.6,2.1,10,41.8,17.8,NaN
2,1959,3,10.6,4.2,0,50.9,85.7,NaN
3,1959,4,13,5.2,0,76.3,125.1,NaN
4,1959,5,18.1,7.9,0,24,222,NaN
...,...,...,...,...,...,...,...,...
741,2020,10,12.9*,7.1*,0*,185.3*,76.8*,Provisional
742,2020,11,10.6*,6.0*,0*,142.4*,29.3*,Provisional
743,2020,12,6.9*,2.6*,8*,131.0*,31.6*,Provisional
744,2021,1,4.9*,-0.2*,14*,132.2*,51.0*,Provisional
745,2021,2,7.0*,2.3*,8*,144.3*,58.8*,Provisional

---
### Exercise 1 - find estimated values and replace with zero

When data is collected dynamically, there are times when it might not be available.  This might be dealt with by leaving a cell blank in the data table, or by estimating a value (and marking it as estimated).

In this data set, any data item that is estimated is marked with a "*" (see the last rows of the data table)

You are going to replace estimated data values with blank ("") and print a message each time you do this, so that you will have an idea of how many estimated items there are.

### Your task
Write a function called **blank_estimated_data()** which will do the following:

*  create a list from the `af (days)` column of the weather_data table (this has been done for you)
*  print the length of the list (Expected: 746)
*  loop through the list and for each item that contains a "*", change the item to "" and print the message "Item blanked" (Expected - there will obviously be many less than 746 but too many to count)  

**Expected output**  
Item blanked  
Item blanked  
Item blanked  
....
(121 times)

In [ ]:
def blank_estimated_data():
  frost_data = list(weather_data["af (days)"])
  # add your code here
  frost_data = list(weather_data["af (days)"])
  for i in range(0, len(frost_data)):
    if "*" in frost_data[i]:
      frost_data[i] = frost_data[i].replace("*", "")
      print("Item blanked")

blank_estimated_data()

Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked
Item blanked

---
### Exercise 2 - count the estimated items

Write the same function again, this time calling it **count_estimated_data()**, finding and blanking items containing "*", but this time instead of printing "Item blanked", you will count it.  Once the loop is finished, you will be able to print the number of estimated items (Expected: 121).

This [video](https://vimeo.com/995077288/f0f775f674?share=copy) will give you some information about how to count items within a loop.

**Expected output**  
121

In [ ]:
def count_estimated_data():
  # add your code here
  frost_data = list(weather_data["af (days)"])
  count_data = 0
  for i in range(0, len(frost_data)):
    if "*" in frost_data[i]:
      count_data = count_data + 1
  print(count_data)

count_estimated_data()

121

---
### Exercise 3 - calculate the average number of days per month when there was actually air frost (not counting the estimated data).

Write a function called **calculate_average_air_frost_days()** which will:
*  create a list from the `af (days)` column of the weather_data table
*  create a new list called **clean_frost_data**
*  use a loop to append all the actual values to this list (ie those without *), remember this is a CSV file so the values will be strings, they should be converted to integer using `int(item)`
*  calculate, and print, the average number of days from this new list.

**Expected output**  
Total 625  
Average 3.2176

In [ ]:
def calculate_average_air_frost_days():
  # add your code here
  datalist = list(weather_data["af (days)"])
  clean_frost_data = []
  for i in range(0, len(datalist)):
    if "*" not in datalist[i]:
      clean_frost_data.append(int(datalist[i]))
  total = len(clean_frost_data)
  average = sum(clean_frost_data)/len(clean_frost_data)
  print(f"Total {total}")
  print(f"Average {average}")

calculate_average_air_frost_days()

Total 625
Average 3.2176

---
### Exercise 4 - create a list of all the years that have a full set of 12 months data

Write a function called **find_full_years()** that will:  
*  create a list from the `yyyy` column of the weather_data table, call this list **years**
*  create a second, empty, list called **full_years**
*  loop through the `full_years` list and, for each year, do the following:
* * count the number of times that year appears in the list
* * if it is 12 (it has 12 separate month entries) then append that year to the full_years list BUT ONLY IF is isn't already in the list
*  print the full_years list

**Expected output**  
  
[1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

In [ ]:

def find_full_years():
  # add your code here
  years = list(weather_data["yyyy"])
  full_years = []
  for i in range(0, len(years)):
    count = years.count(years[i])
    if count == 12 and years[i] not in full_years:
      full_years.append(years[i])
  print(full_years)

find_full_years()

[1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

---
### Exercise 5 - remove the corresponding items in years and months list where there is not a whole year of data

Write a function called **remove_partial_years()** that will process two lists (year and month) and will remove all entries that are for years that don't have a full 12 months data.

This [video](https://vimeo.com/996692129/eac1bc1011?share=copy) demonstrates removing items from two lists together

*  create a list called `years` to hold the `yyyy` column
*  create a list called `months` to hold the `mm` column
*  loop through the `years` list and for each year that doesn't have 12 months:
* *  get the position of the current item using the `.index()` method (ie `item_pos = years.index(item)`)
* * remove the item at the same position in the months list, using the `.pop()` method to remove an item at a given position (ie `.pop(item_pos)`)
* * remove the item from the years list (you can use `.remove(item`) or `pop(item_pos)`, either will work but `.pop(item_pos)` should be safer, ensuring that you remove from exactly the same position in each list
* print the length of both lists to check that the same number of items have been removed from each.  

**Note**:  This process works as long as the two lists are processed at the same time, otherwise the positioning of the items in one may become different from the items in the other.

**Expected output**  
745  
745

In [16]:
def remove_partial_years():
  # add your code here
  years = list(weather_data["yyyy"])
  months = list(weather_data["mm"])
  for item in years:
    if years.count(item) != 12:
      item_pos = years.index(item)
      years.remove(item)
      months.pop(item_pos)
      print(len(years))
      print(len(months))

remove_partial_years()

745
745

# Data validation challenge
---  

#### Have a go at this challenging problem - you will need to do it in stages
A function will find an average weight gain from 6 weight readings (in kg) for a baby grey seal at a sanctuary, weights are measured once per week from birth.  When the data was entered, the data should have been 20, 30, 40, 50, 60, 70 (the pup was 10kg at birth and has gained 10kg per week which is perfect).  

However, the actual data entered was "20", "30", "4=0", "50", "=60", "70".

These numbers are all strings because they were processed into text files for easier storage.  They would need to be converted when the data is processed to get the average.  It is possible that this anomaly is a known problem and so it would be useful to have a function that would clean out the "=" so that all can be easily converted to integers for processing.

It could be quite dangerous for someone to act on a wrong result, maybe heavily overfeeding a perfectly healthy pup.

The code below has two functions that deal with the weights.

The first, **clean_weights()** is blank, for you to complete.  This should:
*  create an empty list called **cleaned_weights**  
*  loop through the weights list and for each number string that contains "=", remove the "=", then convert the number into an integer and append it to the `cleaned_weights` list

The second, **calculate_average_weekly_gain_from_clean_data()** is already tested and will read the weight gain for each each week, calculate and prints the average weight gain for number of weeks recorded.  It will only work if the data is clean and all the numbers are there and in number format.  

#### Your task
1.  Run the code cell - the code will crash as the weights have not been cleaned (`TypeError` - these are strings not numbers).
2.  Remove the # from the line that says `# weights = clean_weights()`
3.  Run the code again - the code will crash again as the weights list is now empty (the first line of the clean_weights() function creates and empty list which becomes the new weights list and this causes an `UnboundLocalError` because it tried to print an average that hadn't been created)
4. Write the `clean_weights()` function as specified above, the expected output will be that the `average_weight_gain` is 10)
5. Change the number "70" to "100" and check that the `average_weight_gain` changes accordingly.  This tells us that the function will work even if the differences are not all 10.

In [ ]:
def clean_weights():
  # add YOUR code here to clean the data by removing the "-"" from the numbers, then converting them to integers (e.g. int(weight))
  cleaned_weights = []




  return cleaned_weights


# calculate and print the average weight gain over all 6 weeks
def calculate_average_weekly_gain_from_clean_data():
  birth_weight = 10
  total_weight_gain = 0
  for i in range(len(weights)-1):
    if i > 0:
      weight_gain = weights[i+1] - weights[i]
    else:
      weight_gain = weights[0] - birth_weight
    total_weight_gain = total_weight_gain + weight_gain
    average_weight_gain = total_weight_gain / len(weights)-1
  print(average_weight_gain)


weights = ["10", "20", "30", "4-0", "50", "-60"]
# weights = clean_weights()
calculate_average_weekly_gain_from_clean_data()

----
# Takeaways

*  data can be invalid in a range of ways (wrong type, missing, wrong format, out of range)
*  data cleaning is the process of manipulating the data to ensure that it is in a form that will mean that statistics created from it will be reasonable.
*  where two or more lists are corresponding, when you remove an item from one list, you must remove the item from the same place in the other list, so that the lists still line up.

## Your thoughts on what you have learnt
Please add some comments in the box below to reflect on what you have learnt through completing this worksheet, and any problems you encountered while doing so.